# Generated by Django 6.0.4 on 2026-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
